#!/bin/bash

# Simple bash script to quickly create the neeede directories to move, copy and/or erase the conf and rc files

mkdir -p $HOME/.local/{bin,share} &&
mkdir -p $HOME/.local/share/fonts/ &&
mkdir -p $HOME/.config/{bat,lsd,fd-find,vim,nvim,feh,nitrogen,rofi,dmenu} &&
mkdir -p $HOME/.config/tiling-wm/{bar,wm,compositor,bin} &&

# Destination of all the modules and scripts for polybar, rofi and sxhkd scripts triggered keyboard shortcuts $HOME/.config/tiling-wm/bin/